# Generated by Django 5.2.7 on 2026-02-03 16:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Ngày học')),
                ('duration_minutes', models.IntegerField(default=0, verbose_name='Thời lượng (phút)')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Buổi học',
                'verbose_name_plural': 'Các buổi học',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Vocabulary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chinese', models.CharField(max_length=100, verbose_name='Tiếng Trung')),
                ('pinyin', models.CharField(blank=True, max_length=100, null=True, verbose_name='Phiên âm')),
                ('vietnamese', models.CharField(max_length=200, verbose_name='Nghĩa tiếng Việt')),
                ('example_sentence', models.TextField(blank=True, null=True, verbose_name='Câu ví dụ')),
                ('learned_date', models.DateField(default=django.utils.timezone.now, verbose_name='Ngày học')),
                ('mastery_level', models.IntegerField(default=1, verbose_name='Độ thuần thục (1-5)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vocabularies', to='home.studysession')),
            ],
            options={
                'verbose_name': 'Từ vựng',
                'verbose_name_plural': 'Từ vựng',
                'ordering': ['-learned_date'],
            },
        ),
    ]
